#################################
#   SUSTAIN       Makefile      #
#################################

INCLUDE	= 	-I/usr/local/mpich/include \
		-I/usr/local/pgapack/include \
		-I../../config \
		-I../../cog
		
LIBS    =  	../../cog/libcogc++.a \
		/usr/local/lib/libpgaO.a \
		/usr/local/mpich/lib/libmpich.a

		

SRCS = 	SUSTAINCatUnit.cpp \
		SUSTAINCluster.cpp \
		SUSTAINDimension.cpp \
		SUSTAINModel.cpp \
		SUSTAINNetwork.cpp \
		main.cpp
		
OBJS = 	SUSTAINCatUnit.o \
		SUSTAINCluster.o \
		SUSTAINDimension.o \
		SUSTAINModel.o \
		SUSTAINNetwork.o \
		main.o
		


@echo ====================================================


default: sustain

#################
#  The Target   #
#################

sustain: $(OBJS)
	@echo Creating sustain executable
	@$(CXX) $(INCLUDE) $(OBJS) $(LIBS) -o sustain
	@echo ====================================================
	@echo If there are no error messages above then the
	@echo sustain models has been created in 
	@echo sustain
	@echo ====================================================
		
###################
# The Source Code #
###################

main.o: main.cpp
	@echo ----  Compiling $< using $(CXX)
	@$(CXX) $(INCLUDE) -c $(CFLAGS) $< -o main.o
	
SUSTAINCatUnit.o: SUSTAINCatUnit.cpp SUSTAINCatUnit.h
	@echo ----  Compiling  $< using $(CXX)
	@$(CXX) $(INCLUDE) -c $(CFLAGS)  $< -o SUSTAINCatUnit.o

SUSTAINCluster.o: SUSTAINCluster.cpp SUSTAINCluster.h
	@echo ----  Compiling  $< using $(CXX) 
	@$(CXX) $(INCLUDE) -c $(CFLAGS)  $< -o SUSTAINCluster.o
	
SUSTAINDimension.o: SUSTAINDimension.cpp SUSTAINDimension.h
	@echo ----  Compiling  $< using $(CXX)
	@$(CXX) $(INCLUDE) -c $(CFLAGS)  $< -o SUSTAINDimension.o
	
SUSTAINModel.o: SUSTAINModel.cpp SUSTAINModel.h
	@echo ----  Compiling  $< using $(CXX)
	@$(CXX) $(INCLUDE) -c $(CFLAGS)  $< -o SUSTAINModel.o
	
SUSTAINNetwork.o: SUSTAINNetwork.cpp SUSTAINNetwork.h
	@echo ----  Compiling  $< using $(CXX)
	@$(CXX) $(INCLUDE) -c $(CFLAGS)  $< -o SUSTAINNetwork.o

depend: $(SRCS)
	$(DEPEND) $(SRCS)
	
clean:
	@echo Removing all temporary items and compilation products
	rm -f *.o sustain