# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slpBM <- function(st, tr, xtdo = FALSE) {
    .Call(`_catlearn_slpBM`, st, tr, xtdo)
}

slpDGCM <- function(st, test, dec = "BIAS", exemplar_mute = FALSE, exemplar_decay = TRUE) {
    .Call(`_catlearn_slpDGCM`, st, test, dec, exemplar_mute, exemplar_decay)
}

slpEXIT <- function(st, tr, xtdo = FALSE) {
    .Call(`_catlearn_slpEXIT`, st, tr, xtdo)
}

slpLMSnet <- function(st, tr, xtdo = FALSE, dec = "logistic") {
    .Call(`_catlearn_slpLMSnet`, st, tr, xtdo, dec)
}

slpMack75 <- function(st, tr, xtdo = FALSE) {
    .Call(`_catlearn_slpMack75`, st, tr, xtdo)
}

slpNNCAG <- function(st, tr, xtdo = FALSE) {
    .Call(`_catlearn_slpNNCAG`, st, tr, xtdo)
}

slpNNRAS <- function(st, tr, xtdo = FALSE) {
    .Call(`_catlearn_slpNNRAS`, st, tr, xtdo)
}

slpRW <- function(st, tr, xtdo = FALSE) {
    .Call(`_catlearn_slpRW`, st, tr, xtdo)
}

slpALCOVE <- function(st, tr, dec = "ER", humble = TRUE, attcon = FALSE, absval = -1, xtdo = FALSE) {
    .Call(`_catlearn_slpALCOVE`, st, tr, dec, humble, attcon, absval, xtdo)
}

slpCOVIS <- function(st, tr, crx = TRUE, respt = FALSE, rgive = TRUE, xtdo = FALSE) {
    .Call(`_catlearn_slpCOVIS`, st, tr, crx, respt, rgive, xtdo)
}

