# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slpALCOVE <- function(st, tr, dec = "ER", humble = TRUE, attcon = FALSE, absval = -1, xtdo = FALSE) {
    .Call('_catlearn_slpALCOVE', PACKAGE = 'catlearn', st, tr, dec, humble, attcon, absval, xtdo)
}

slpBM <- function(st, tr, xtdo = FALSE) {
    .Call('_catlearn_slpBM', PACKAGE = 'catlearn', st, tr, xtdo)
}

slpCOVIS <- function(st, tr, crx = TRUE, respt = FALSE, rgive = TRUE, xtdo = FALSE) {
    .Call('_catlearn_slpCOVIS', PACKAGE = 'catlearn', st, tr, crx, respt, rgive, xtdo)
}

slpRW <- function(st, tr, xtdo = FALSE) {
    .Call('_catlearn_slpRW', PACKAGE = 'catlearn', st, tr, xtdo)
}

